name: Setup Branch Protection

on:
  workflow_dispatch:

jobs:
  setup-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Setup branch protection rules
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Set up branch protection for main branch
            try {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'main',
                required_status_checks: {
                  strict: true,
                  contexts: ['amazon-q-review']
                },
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: false
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false
              });
              
              console.log('✅ Branch protection rules set up successfully!');
            } catch (error) {
              console.log('Branch protection setup:', error.message);
            }
